app = "ddj-flx-6-midi-logger-4"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  SINGLE_PORT = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    soft_limit = 300
    hard_limit = 500

  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    method   = "GET"
    path     = "/healthz"
