# fly.toml

app = "ddj-flx-6-midi-logger-4"   # kept original app name to avoid breaking deploys

[build]
  dockerfile = "Dockerfile"       # kept original Dockerfile build

[env]
  NODE_ENV = "production"
  SINGLE_PORT = "1"

# We keep your newer-style [http_service] (from the original)
# and merge in the explicit 80/443 handler blocks + keep-alive knobs.
[http_service]
  internal_port = 8080            # kept original app port (your server listens here)
  force_https = true              # from original
  auto_start_machines = true      # merged/kept
  auto_stop_machines  = false     # merged/kept
  min_machines_running = 1        # merged/kept

  # Keep your original concurrency (300/500) to avoid behavior change.
  [http_service.concurrency]
    type = "connections"
    soft_limit = 300
    hard_limit = 500

  # Explicit port handler mappings (merged from your addition)
  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health check from your original (unchanged)
  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    method   = "GET"
    path     = "/healthz"
